DEVICE_PATH := device/poco/mgvi_64_64only_armv82

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_SUPPORTS_64_BIT_APPS := true

TARGET_BOARD_PLATFORM := mt6985
BOARD_HAS_MTK_HARDWARE := true
TARGET_NO_KERNEL := true

BOARD_BOOT_HEADER_VERSION := 3
BOARD_BUILD_VENDOR_BOOT_IMAGE := true
BOARD_USES_VENDOR_BOOT := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true

BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_PREBUILT_DTBIMAGE_DIR := $(DEVICE_PATH)

TW_THEME := portrait_hdpi
TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 2400
TW_MAX_BRIGHTNESS := 2047
TW_DEFAULT_BRIGHTNESS := 1200

OFOX_AB_DEVICE := true
FOX_VIRTUAL_AB_DEVICE := true
FOX_RECOVERY_INSTALL_PARTITION := "/vendor_boot"
FOX_RECOVERY_VENDOR_PARTITION := "/vendor_boot"
OF_MAINTAINER := Ahmed Tawfik
BOARD_MKBOOTIMG_ARGS += --header_version 3
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/dtb.img
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)
BOARD_PREBUILT_VENDOR_RAMDISK_DIRS += device/poco/mgvi_64_64only_armv82/vendor_ramdisk
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
