DEVICE_PATH := device/poco/mgvi_64_64only_armv82

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_SUPPORTS_64_BIT_APPS := true

TARGET_BOARD_PLATFORM := mt6991
BOARD_HAS_MTK_HARDWARE := true
TARGET_NO_KERNEL := true

# Boot Image & DTB Configuration
BOARD_BOOT_HEADER_VERSION := 4
BOARD_PAGE_SIZE := 4096
BOARD_MKBOOTIMG_ARGS += --header_version 4
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/dtb.img
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)
BOARD_PREBUILT_DTBIMAGE_DIR := $(DEVICE_PATH)
BOARD_PREBUILT_VENDOR_RAMDISK_DIRS += $(DEVICE_PATH)/vendor_ramdisk
BOARD_RAMDISK_USE_LZ4 := true

# TWRP/OrangeFox UI Settings
TW_THEME := portrait_hdpi
TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 2400
TW_MAX_BRIGHTNESS := 2047
TW_DEFAULT_BRIGHTNESS := 1200

# OrangeFox Specific Settings
OFOX_AB_DEVICE := true
FOX_VIRTUAL_AB_DEVICE := true
FOX_RECOVERY_INSTALL_PARTITION := "/vendor_boot"
FOX_RECOVERY_VENDOR_PARTITION := "/vendor_boot"
OF_MAINTAINER := Ahmed Tawfik

# OrangeFox vendor_boot configuration
BOARD_BUILD_VENDOR_BOOT_IMAGE := true
BOARD_USES_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
TARGET_NO_RECOVERY := true

# AVB Patching
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3

# Fix for vendor root symlink conflict at 99%
BOARD_ROOT_EXTRA_FOLDERS += vendor

# Partition Sizes (لحاجات التشفير الخاصة بأداة AVB)
BOARD_BOOTIMAGE_PARTITION_SIZE := 134217728
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
